language: python
# python versions to use during the tests
python:
    - "2.7"
install:
    - pip install coverage
    - pip install coveralls
# command to run tests
script:
    - coverage  run  -m unittest discover -p 'test*.py'
branches:
  only:
   - master
after_success:
    - coveralls